Day55/projectsMaintenance/config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  get 'about' => 'pages#about'

  resources :projects

end

Day55/projectsMaintenance/app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence:true,length: {minimum: 5}


end

Day55/projectsMaintenance/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Day55/projectsMaintenance/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title="About"

  end
end

Day55/projectsMaintenance/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @project =Project.all

  end

  def show
    @project= Project.find(params[:id])
  end

  def new

  end

  def create
      # render plain: params[:project].inspect
      @project=  Project.new(project_params)
      if(@project.save)
        redirect_to @project
      else
        render 'new'
      end

  end

  def edit
    @project= Project.find(params[:id])

  end

  def update
    @project= Project.find(params[:id])
    if(@project.update(project_params))
      redirect_to @project
    else
      render 'edit'
    end

  end

  def destroy
    @project= Project.find(params[:id])
    @project.destroy
    redirect_to @project
  end

  private def project_params
    params.require(:project).permit(:title,:body)
  end

end

Day55/projectsMaintenance/app/helpers/application_helper.rb
module ApplicationHelper
end

Day55/projectsMaintenance/app/helpers/pages_helper.rb
module PagesHelper
end

Day55/projectsMaintenance/app/helpers/projects_helper.rb
module ProjectsHelper
end

Day55/projectsMaintenance/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectsMaintenance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Day55/projectsMaintenance/app/views/pages/about.html.erb
<h1><%= @title %></h1>

Day55/projectsMaintenance/app/views/projects/edit.html.erb
<h1> Edit Project </h1>
<%= form_for :project, url:project_path(@project), method: :patch do |p| %>
  <p>
    <%= p.label :title %><br>
    <%= p.text_field :title %>
  </p>

  <p>
    <%= p.label :body %><br>
    <%= p.text_area :body %>
  </p>

  <p>
     <%= p.submit %>
  </p>

<% end %>

Day55/projectsMaintenance/app/views/projects/index.html.erb
<h1>Project Views</h1>
<%= @project.each do |p| %>
<h3><%= p.title %></h3>
<p><%= p.body %></p>
<button type="button" name="button"> <%= link_to "READ More", project_path(p) %> </button>
<% end %>

Day55/projectsMaintenance/app/views/projects/new.html.erb
<h1> Add Project </h1>
<%= form_for :project, url:projects_path do |p| %>
  <p>
    <%= p.label :title %><br>
    <%= p.text_field :title %>
  </p>

  <p>
    <%= p.label :body %><br>
    <%= p.text_area :body %>
  </p>

  <p>
     <%= p.submit %>
  </p>

<% end %>

Day55/projectsMaintenance/app/views/projects/show.html.erb
<h2> <%= @project.title %> </h2>
<p>  <%=  @project.body  %> </p>
<hr>
<button type="button" name="button"> <%= link_to "Edit", edit_project_path(@project) %> </button>
<button type="button" name="button"> <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: 'Are you sure?'} %> </button>